import { ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navigation } from "@components/navigation";
import { AppProviders } from "@components/appProviders";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} min-h-screen flex flex-col justify-start items-stretch dark:bg-gray-900`}
      >
        <AppProviders>
          <Navigation />

          {children}
        </AppProviders>
      </body>
    </html>
  );
}
